### ISSUE TITLE
Integration of xplt into xsuite

### ISSUE THREAD

**Issue by eltos** [xsuite/xplt#5]
Following discussions with @giadarol and @eltos last week, we want to add xplt to the xsuite collection

- [x] Clarify preconditions / responsibilities (see below, by @giadarol @eltos @rdemaria @szymonlopaciuk)
- [x] Add @eltos to github.com/xsuite group (by @giadarol, at least temporary to allow moving the repo there)
- [x] Move repository github.com/eltos/xplt to github.com/xsuite/xplt (by @eltos)
- [x] Add @giadarol and @rdemaria as maintainer on PyPI (by @eltos, deployment is fully automated via GitHub action, but just in case)
- [x] Update xsuite examples and documentation to use xplt plots

I have added some guidelines and core concept description of xplt at https://github.com/eltos/xplt/wiki

Some things to clarify (we talked about it, but just to be sure)
- @eltos will keep using and updating the library for his daily needs, likely on a separate branch and merging, publishing versions etc. in the short term
- @giadarol will keep the library working with future updates / possible API changes of xsuite in the long term
- On short term, the existing basic functionality remains somewhat independent of xsuite (i.e. no imports), since many of the spill and slow extraction related plots work and are being used with data from different sources (including detector data from measurements) and e.g. floor plan plotting of a sequence before/after conversion from MAD-X is useful
  > As from the docs:
  > _Xsuite is not an explicit dependency, rather an API assumption on available attributes, indices and units. You can use data from any source, and also custom attributes. See [examples/properties](https://eltos.github.io/xplt/examples/properties.html) on how to specify units of custom attributes._
- New functionality can rely on xsuite specific implementation details when required
- Automated testing is currently done only by checking for exceptions, not by image comparison of actual output.

**Comment by eltos** [comment]
@giadarol do you agree? Anything to add?

**Comment by szymonlopaciuk** [comment]
@eltos I have added you to the organisation. Once you request the transfer of Xplt (Settings > General > Danger Zone) we will approve it and make sure the permissions are set up right so that you can manage it.

**Comment by eltos** [comment]
@szymonlopaciuk looks good, PYPI tokens have been transferred, release action is working, docs are online at https://xsuite.github.io/xplt

**Comment by szymonlopaciuk** [comment]
Perfect! I've made you admin on the repository, so you should retain all the rights that you've had so far.

**Comment by eltos** [comment]
Added a first example to the docs, see https://github.com/xsuite/xtrack/pull/477 and https://github.com/xsuite/xsuite/pull/487
